[versions]
agp = "8.13.1"
androidx-annotation = "1.9.1"
androidx-core-ktx = "1.17.0"
compose-lint-checks = "1.4.2"
compose-material3 = "1.4.0"
compose-ui = "1.10.0"
google-accompanist-permissions = "0.37.3"
junit = "4.13.2"
kotlin = "2.2.21"
kover = "0.9.3"
ktlint = "14.0.1"
robolectric = "4.16"
uiTestJunit4Android = "1.10.0"
versionCatalogUpdate = "1.0.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "uiTestJunit4Android" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "google-accompanist-permissions" }
junit = { module = "junit:junit", version.ref = "junit" }
roboelectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
